import type { SchemaProperties,Obj } from '@/model'
export default {
    title1:{
        type:'divider',
        label:'标题',
        component:{
            title:'标题'
        },
        formLayout:false
    },
    'option.title.show':{
        type:'switch',
        label:'显示标题',
    },
    'option.title.text':{
        type:'string',
        label:'标题文本',
    },
    'option.title.link':{
        type:'string',
        label:'文本超链接',
    },
    title2:{
        type:'divider',
        label:'布局',
        component:{
            title:'布局'
        },
        formLayout:false
    },
    'option.grid.left':{
        type:'string',
        label:'左边距',
    },
    'option.grid.right':{
        type:'string',
        label:'右边距',
    },
    'option.grid.top':{
        type:'string',
        label:'上边距',
    },
    'option.grid.bottom':{
        type:'string',
        label:'下边距',
    },
    title3:{
        type:'divider',
        label:'图例',
        component:{
            title:'图例'
        },
        formLayout:false
    },
    'option.legend.show':{
        type:'switch',
        label:'显示图例',
    },
    'option.legend.type':{
        type:'select',
        label:'图例类型',
        component:{
            dataSource:[
                {
                    label:'普通图例',
                    value:'plain'
                },{
                    label:'翻页图例',
                    value:'scroll'
                }
            ]
        }
    },
    'option.legend.orient':{
        type:'select',
        label:'图例朝向',
        component:{
            dataSource:[
                {
                    value:'horizontal',
                    label:'横向'
                },
                {
                    value:'vertical',
                    label:'纵向'
                }
            ]
        }
    },
    title4:{
        type:'divider',
        label:'边框',
        component:{
            title:'边框'
        },
        formLayout:false
    },
    borderWidth:{
        type:'string',
        label:'边框宽度',
        tooltip: '请注明单位，一般为：px'
    },
    borderColor:{
        type:'string',
        label:'边框颜色',
        component:{
            name:'color-picker'
        }
    },
    borderStyle:{
        type:'radio',
        label:'边框样式',
        component:{
            dataSource:[
                {
                    label:'无边框',
                    value:'none'
                },
                {
                    label:'虚线',
                    value:'dashed'
                },
                {
                    label:'实线',
                    value:'solid'
                }
            ],
            buttonStyle:"solid"
        }
    },
    borderRadius:{
        type:'string',
        label:'边框圆角',
        tooltip: '请注明单位，可以为%或者px'
    }
} as Obj<SchemaProperties>